services:
  mongo:
    image: mongo:7.0
    expose:
      - 27017
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=45minutes
    volumes:
      - mongo_data:/data/db
    networks:
      - internal

  backend:
    image: python:3.11
    working_dir: /app
    depends_on:
      - mongo
    expose:
      - 80
    ports:
      - 8080:80
    volumes: 
      - ./backend:/app
    networks:
      - internal   
    command: bash -c 'pip install . ; python start.py --reload'
    environment:
      - DATABASE_NAME=45minutes
      - DATABASE_URL=${DATABASE_URL:-mongodb://mongo:27017}
      - ENV=dev
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}
      - client_id=${GOOGLE_CLIENT_ID}
      - client_secret=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI:-http://localhost:8080/reuniones/auth/auth/callback}
      - TEST=true
      - BASE_URL=http://localhost:5173
      - DEVELOPMENT=true
  backoffice:
    build:
      context: ./backoffice
    image: node # Usa la versión de Node que necesites
    working_dir: /app
    depends_on:
      - backend
    expose:
      - 5173
    ports:
      - "5173:5173"
    volumes:
      - ./backoffice:/app
      - backoffice_node_modules:/app/node_modules  # Usa un volumen persistente
    networks:
      - internal
    environment:
      - SECRET_BACKEND_URL=http://backend:8000
      - NODE_ENV=development
      - VITE_APP_DEV=false
      - VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY}
      - VITE_APP_API_URL=${VITE_APP_API_URL:-http://localhost:8080}
    command: "bash -c 'npm i && npm run dev -- --host 0.0.0.0 --port 5173'"
volumes:
  backoffice_node_modules:  # Define el volumen persistente para node_modules
  mongo_data:
  


networks:
  internal:
